# Site settings
title: Szymon Motyka
email: szymon@lifelike.pl
description:  SzymonMotyka.pl Twoj blog o technologii
baseurl: "" # the subpath of your site, e.g. /blog/
url: "aluspl.github.io" # the base hostname & protocol for your site
twitter_username: aluspl
github_username:  aluspl

# Build settings
markdown: kramdown
